### PR TITLE
Make compatible with moor 4.3.0

### PR DESCRIPTION
**Pull request by justacid**
Hi!

Moor 4.3.0 caused a breaking change. Because moor now allows custom data classes 
starting with 4.3.0 the type List<TableInfo<Table, DataClass>> needs to be changed
to List<TableInfo<Table, dynamic>>. This PR does just that.

Also regenerates the example db and bumps version number.

### CODE REVIEW

**Review by vanlooverenkoen — CHANGES_REQUESTED** [review]
I just did the refactor myself and you missed some files that still need to be migrated.

**Comment by justacid** [comment]
How do you want to proceed? Do you have some pointers or do you want to close this PR?

**Comment by vanlooverenkoen** [comment]
I will do some extra testing and I will create a new pull request. Thanks for your contribution and for giving the first steps on how we can fix this issue.

**Comment by justacid** [comment]
All right! Thanks! 👍🏻

**Comment by vanlooverenkoen** [comment]
fixed in 4.0.0

**Pull request closed without merging**
