### PR TITLE
Upgrade for Provider v6 support

### LINKED ISSUE #47: Support to newest version of moor
Hello when i upgarde moor to lastest version i have exception like this.
`
Because moor_db_viewer 4.3.0 depends on provider ^5.0.0 and no versions of moor_db_viewer match >4.3.0 <5.0.0, moor_db_viewer ^4.3.0 requires provider ^5.0.0.
So, because my_app depends on both moor_db_viewer ^4.3.0 and provider ^6.0.0, version solving failed.
pub get failed (1; So, because my_app depends on both moor_db_viewer ^4.3.0 and provider ^6.0.0, version solving failed.)`

### PR DESCRIPTION
**Pull request by juliangeissler**
Also upgrade to latest moor and upgrade example

Fixes #47

### CODE REVIEW

**Comment by vanlooverenkoen** [comment]
I will take a look at it today. I am just back from holiday

**Comment by juliangeissler** [comment]
cool, welcome back :)

**Comment by vanlooverenkoen** [comment]
Moor is already updated to 4.5.0 do you want to add that in this pull request or do we create a new one?

**Review by vanlooverenkoen — CHANGES_REQUESTED** [review]
Moor is already updated to 4.5.0

**Comment by juliangeissler** [comment]
Upgraded Moor

**Comment by vanlooverenkoen** [comment]
published 4.4.0

**Pull request merged**
